### PR TITLE
ignore 404(not_found) status for delete and update

### PR DESCRIPTION
**Pull request by fpintoppb**

### CODE REVIEW

**Comment by fopina** [comment]
I might miss context: what is a 404 during update?
Will the document be created or not?

**Comment by fpintoppb** [comment]
> I might miss context: what is a 404 during update? Will the document be created or not?

a 404 is when we are trying to update a document that does not exist. 

The idea here is just to ignore the ones that do not exist and guarantee that we update the existing ones and we don´t break the collector. As it is the collector breaks for documents that do not exist

**Comment by fopina** [comment]
But then "updates" (that should've been creates) are lost?
That does not seem like the best way. Is this change related to an ES upgrade? Or is it only with some new collector?
How to reproduce those update 404s?

**Comment by fpintoppb** [comment]
This is a change related to a new collector yes, that uses the `_op_type=update`, just to update a specific field on the documents. New documents should be "create" and not update right?

**Pull request closed without merging**
